{{- if .Values.deployment.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "containerinfo.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "containerinfo.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "containerinfo.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}