{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
  labels:
  {{- include "containerinfo.labels" . | nindent 4 }}
spec:
  controller: nginx.org/ingress-controller
{{- end }}