name: "Build-Push-Scan-Deploy"

on:
  workflow_dispatch: # Ondemand Run
    branches:
      - main
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
    # paths-ignore: ".github/**"

env:

  # General
  DOCKER_REGISTRY   : dushansri
  DOCKER_BUILDKIT   : 1
  DOCKER_PLATFORM   : "linux/arm64"

  # Pull Request ENV
  # Set PR and SHA for repository_dispatch
  PR: ${{ github.event.pull_request.number }}
  SHA: ${{ github.event.pull_request.head.sha }}

# ------------------
jobs:
  build-push-api:
    name: Build & Push Api
    runs-on: ubuntu-latest
    # Run the job if it is not a scheduled or draft PR
    if: github.event_name != 'schedule' && github.event.pull_request.draft != true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #Setup ARM64 dependancies
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Docker Hub Registry login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # SET Image Tag
      - name: Set Tag
        run: echo TAG=$(git rev-parse --short $SHA) >> $GITHUB_ENV
      - name: Display Tag
        run: echo $TAG
      # Building and pushing the Image to Docker Hub
      - name: Build & Push Image
        working-directory: api/
        run: |
          BASE_IMAGE=$DOCKER_REGISTRY/containerinfo
          docker pull --platform $DOCKER_PLATFORM $BASE_IMAGE:latest || echo "Warning: $BASE_IMAGE:latest not found, continuing..."
          
          docker buildx build \
                        --pull \
                        --push \
                        --platform $DOCKER_PLATFORM \
                        -t $BASE_IMAGE:$TAG \
                        -t $BASE_IMAGE:latest \
                        -f Dockerfile \
                        --cache-from $BASE_IMAGE:latest .
      - name: List dirs
        run: |
          ls -la /tmp/.buildx*
          ls -la /var/lib/docker/

  scan:
    name: Scan Image
    runs-on: ubuntu-20.04
    needs:
     - build-push-api
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Docker Hub Registry login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # SET Image Tag
      - name: Set Tag
        run: echo TAG=$(git rev-parse --short $SHA) >> $GITHUB_ENV
      - name: Display Tag
        run: echo $TAG
      - name: Pull Image
        run: |
          BASE_IMAGE=$DOCKER_REGISTRY/containerinfo
          echo BASE_IMAGE=$BASE_IMAGE >> $GITHUB_ENV
          docker pull --platform $DOCKER_PLATFORM $BASE_IMAGE:$TAG
      # Vulnerability Scan
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: '${{ env.BASE_IMAGE }}:${{ env.TAG }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
